config/routes.rb
ZS::Application.routes.draw do

  devise_for :users

  root to: 'home#index'

  resources :bars
  resources :parties
  resources :clubs
  resources :lines
  resources :app_users

  namespace :api do
    get "search"
    get "zuller_my_night"
    get "parties"
  end

end

app/models/line.rb
class Line < Event
  belongs_to :host, class_name: 'Place', inverse_of: :lines

  validates_presence_of :host

  def address
    self.host.address
  end

end

app/controllers/lines_controller.rb
class LinesController < ApplicationController
  before_filter :authenticate_user!
  # GET /lines
  # GET /lines.json
  def index
    @lines = Line.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lines }
    end
  end

  # GET /lines/1
  # GET /lines/1.json
  def show
    @line = Line.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @line }
    end
  end

  # GET /lines/new
  # GET /lines/new.json
  def new
    @line = Line.new

    Attraction.all[0]
    @hosts = Place.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @line }
    end
  end

  # GET /lines/1/edit
  def edit
    @line = Line.find(params[:id])

    Attraction.all[0]
    @hosts = Place.all
  end

  # POST /lines
  # POST /lines.json
  def create
    Attraction.all[0]
    @line = Line.new(params[:line])
    if params[:line][:host].present?
      @host = Place.find(params[:line][:host])
      @host.parties << @line
    end

    respond_to do |format|
      if @line.save
        format.html { redirect_to @line, notice: 'Line was successfully created.' }
        format.json { render json: @line, status: :created, location: @line }
      else
        format.html { render action: "new" }
        format.json { render json: @line.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lines/1
  # PUT /lines/1.json
  def update
    @line = Line.find(params[:id])
    host = Place.find(params[:line][:host])
    params[:line][:host] = host

    respond_to do |format|
      if @line.update_attributes(params[:line])
        format.html { redirect_to @line, notice: 'Line was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @line.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lines/1
  # DELETE /lines/1.json
  def destroy
    @line = Line.find(params[:id])
    @line.destroy

    respond_to do |format|
      format.html { redirect_to lines_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/lines_helper.rb
module LinesHelper
end

app/views/lines/_form.html.haml
= simple_form_for(@line, format: :html) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    - if @line.host.present?
      = f.input :host, collection: @hosts, input_html: { class: "host-select" }, selected: @line.host.id
    - else
      = f.input :host, collection: @hosts, input_html: { class: "host-select" }
    = f.input :phone_number
    = f.input :contact_phone
    = f.label :min_age
    = f.number_field :min_age, min: 18, max: 100, value: 18
    = f.input :logo_url, as: :filepicker, label: "Logo", wrapper_html: { class: "image-picker" }
    = f.input :photos_url, as: :filepicker, label: "Photos", wrapper_html: { class: "image-picker" }
    = f.input :musics, as: :select, input_html: { class: "music-multiselect" }
    = f.input :duration, as: :time, minute_step: 30, input_html: { class: "input-mini" }

  .form-actions
    = f.button :submit, class: "btn btn-primary"

app/views/lines/edit.html.haml
.page-header
  %h1 Editing line

= render 'form'

= link_to 'Show', lines_path(@line, format: :html), class: 'btn'
= link_to 'Back', lines_path(format: :html), class: 'btn'

app/views/lines/index.html.haml
.page-header
  %h1 Line

%table.table.table-striped.table-bordered
  %tr
    %th Name
    %th Host
    %th Address
    %th Phone number
    %th Contact number
    %th Min age
    %th Logo url
    %th Photos url
    %th Musics
    %th Duration
    %th Created At
    %th Weight
    %th

  - Attraction.all[0]
  - @lines.each do |line|
    %tr
      %td= line.name
      %td= line.host.name
      %td= line.address
      %td= line.phone_number
      %td= line.contact_phone
      %td= line.min_age
      %td= line.logo_url
      %td= line.photos_url
      %td= line.musics.join(', ')
      %td= line.duration
      %td= line.created_at
      %td= line.weight
      %td
        = link_to 'Show', line_path(line, format: :html), class: 'btn btn-mini btn-in-table'
        = link_to 'Edit', edit_line_path(line, format: :html), class: 'btn btn-mini btn-in-table'
        = link_to 'Delete', line_path(line, format: :html), method: :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-mini btn-danger btn-in-table'

%br

= link_to new_line_path(format: :html), class: 'btn btn-success' do
  %i.icon-plus.icon-white
  new line

app/views/lines/new.html.haml
.page-header
  %h1 New line

= render 'form'

= link_to 'Back', lines_path(format: :html), class: 'btn'

app/views/lines/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @line.name
%p
  %b Address:
  = @line.address
%p
  %b Phone number:
  = @line.phone_number
%p
  %b Contact phone:
  = @line.contact_phone
%p
  %b Min age:
  = @line.min_age
%p
  %b Logo:
  - if @line.logo_url?
    = filepicker_image_tag @line.logo_url, w: 160, h: 160, fit: 'clip'
  = @line.logo_url
%p
  %b Photos:
  - if @line.photos_url?
    = filepicker_image_tag @line.photos_url, w: 160, h: 160, fit: 'clip'
  = @line.photos_url
%p
  %b Music:
  = @line.musics.join(', ')
%p
  %b Duration:
  = @line.duration
%p
  %b Create At:
  = @line.created_at
%p
  %b Weight:
  = @line.weight

/ = link_to 'Edit', edit_line_path(@line, format: :html), class: 'btn'
= link_to 'Back', lines_path(format: :html), class: 'btn'