config/routes.rb
ZS::Application.routes.draw do

  devise_for :users

  root to: 'home#index'

  resources :bars
  resources :parties
  resources :clubs
  resources :lines
  resources :app_users

  namespace :api do
    get "search"
    get "zuller_my_night"
    get "parties"
  end

end

app/models/party.rb
class Party < Event
  belongs_to :host, class_name: 'Place', inverse_of: :parties
  
  validates_presence_of :host
  
  def address
    self.host.address
  end

end 

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
  before_filter :authenticate_user!
  # GET /parties
  # GET /parties.json
  def index
    @parties = Party.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @parties }
    end
  end

  # GET /parties/1
  # GET /parties/1.json
  def show
    @party = Party.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @party }
    end
  end

  # GET /parties/new
  # GET /parties/new.json
  def new
    @party = Party.new

    Attraction.all[0]
    @hosts = Place.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @party }
    end
  end

  # GET /parties/1/edit
  def edit
    @party = Party.find(params[:id])

    Attraction.all[0]
    @hosts = Place.all
  end

  # POST /parties
  # POST /parties.json
  def create
    Attraction.all[0]
    @party = Party.new(params[:party])
    if params[:party][:host].present?
      @host = Place.find(params[:party][:host])
      @host.parties << @party
    end

    respond_to do |format|
      if @party.save
        format.html { redirect_to @party, notice: 'Party was successfully created.' }
        format.json { render json: @party, status: :created, location: @party }
      else
        format.html { render action: "new" }
        format.json { render json: @party.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /parties/1
  # PUT /parties/1.json
  def update
    @party = Party.find(params[:id])
    host = Place.find(params[:party][:host])
    params[:party][:host] = host

    respond_to do |format|
      if @party.update_attributes(params[:party])
        format.html { redirect_to @party, notice: 'Party was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @party.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parties/1
  # DELETE /parties/1.json
  def destroy
    @party = Party.find(params[:id])
    @party.destroy

    respond_to do |format|
      format.html { redirect_to parties_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/views/parties/_form.html.haml
= simple_form_for(@party, format: :html) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    - if @party.host.present?
      = f.input :host, collection: @hosts, input_html: { class: "host-select" }, selected: @party.host.id
    - else
      = f.input :host, collection: @hosts, input_html: { class: "host-select" }
    = f.input :phone_number
    = f.input :contact_phone
    = f.label :min_age
    = f.number_field :min_age, min: 18, max: 100, value: 18
    = f.input :logo_url, as: :filepicker, label: "Logo", wrapper_html: { class: "image-picker" }
    = f.input :photos_url, as: :filepicker, label: "Photos", wrapper_html: { class: "image-picker" }
    = f.input :musics, as: :select, input_html: { class: "music-multiselect" }
    = f.input :duration, as: :time, minute_step: 30, input_html: { class: "input-mini" }

  .form-actions
    = f.button :submit, class: "btn btn-primary"

app/views/parties/edit.html.haml
.page-header
  %h1 Editing party

= render 'form'

= link_to 'Show', parties_path(@party, format: :html), class: 'btn'
= link_to 'Back', parties_path(format: :html), class: 'btn'

app/views/parties/index.html.haml
.page-header
  %h1 Party

%table.table.table-striped.table-bordered
  %tr
    %th Name
    %th Host
    %th Address
    %th Phone number
    %th Contact number
    %th Min age
    %th Logo url
    %th Photos url
    %th Musics
    %th Duration
    %th Created At
    %th Weight
    %th

  - Attraction.all[0]
  - @parties.each do |party|
    %tr
      %td= party.name
      %td= party.host.name
      %td= party.address
      %td= party.phone_number
      %td= party.contact_phone
      %td= party.min_age
      %td= party.logo_url
      %td= party.photos_url
      %td= party.musics.join(', ')
      %td= party.duration
      %td= party.created_at
      %td= party.weight
      %td
        = link_to 'Show', party_path(party, format: :html), class: 'btn btn-mini btn-in-table'
        = link_to 'Edit', edit_party_path(party, format: :html), class: 'btn btn-mini btn-in-table'
        = link_to 'Delete', party_path(party, format: :html), method: :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-mini btn-danger btn-in-table'

%br

= link_to new_party_path(format: :html), class: 'btn btn-success' do
  %i.icon-plus.icon-white
  new party

app/views/parties/new.html.haml
.page-header
  %h1 New party

= render 'form'

= link_to 'Back', parties_path(format: :html), class: 'btn'

app/views/parties/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @party.name
%p
  %b Address:
  = @party.address
%p
  %b Phone number:
  = @party.phone_number
%p
  %b Contact phone:
  = @party.contact_phone
%p
  %b Min age:
  = @party.min_age
%p
  %b Logo:
  - if @party.logo_url?
    = filepicker_image_tag @party.logo_url, w: 160, h: 160, fit: 'clip'
  = @party.logo_url
%p
  %b Photos:
  - if @party.photos_url?
    = filepicker_image_tag @party.photos_url, w: 160, h: 160, fit: 'clip'
  = @party.photos_url
%p
  %b Music:
  = @party.musics.join(', ')
%p
  %b Duration:
  = @party.duration
%p
  %b Create At:
  = @party.created_at
%p
  %b Weight:
  = @party.weight

/ = link_to 'Edit', edit_party_path(@party, format: :html), class: 'btn'
= link_to 'Back', parties_path(format: :html), class: 'btn'