config/routes.rb
ZS::Application.routes.draw do

  devise_for :users

  root to: 'home#index'

  resources :bars
  resources :parties
  resources :clubs
  resources :lines
  resources :app_users

  namespace :api do
    get "search"
    get "zuller_my_night"
    get "parties"
  end

end

app/models/bar.rb
class Bar < Place
end

app/controllers/bars_controller.rb
class BarsController < ApplicationController
  before_filter :authenticate_user!
  # load_and_authorize_resource

  # GET /bars
  # GET /bars.json
  def index
    @bars = Bar.all

    respond_to do |format|
      format.html # index.html.haml
      format.json { render json: @bars }
    end
  end

  # GET /bars/1
  # GET /bars/1.json
  def show
    @bar = Bar.find(params[:id])

    respond_to do |format|
      format.html # show.html.haml
      format.json { render json: @bar }
    end
  end

  # GET /bars/new
  # GET /bars/new.json
  def new
    @bar = Bar.new

    respond_to do |format|
      format.html # new.html.haml
      format.json { render json: @bar }
    end
  end

  # GET /bars/1/edit
  def edit
    @bar = Bar.find(params[:id])
  end

  # POST /bars
  # POST /bars.json
  def create
    @bar = Bar.new(params[:bar])

    respond_to do |format|
      if @bar.save
        format.html { redirect_to @bar, notice: 'Bar was successfully created.' }
        format.json { render json: @bar, status: :created, location: @bar }
      else
        format.html { render action: "new" }
        format.json { render json: @bar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bars/1
  # PUT /bars/1.json
  def update
    @bar = Bar.find(params[:id])

    respond_to do |format|
      if @bar.update_attributes(params[:bar])
        format.html { redirect_to @bar, notice: 'Bar was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bars/1
  # DELETE /bars/1.json
  def destroy
    @bar = Bar.find(params[:id])
    @bar.destroy

    respond_to do |format|
      format.html { redirect_to bars_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/bars_helper.rb
module BarsHelper
end

app/views/bars/_form.html.haml
= simple_form_for(@bar, format: :html) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :address, input_html: { id: "addresspicker" }
    = f.input :lat, label: 'Latitude'
    = f.input :lng, label: 'Longitude'
    = f.input :phone_number
    = f.input :contact_phone
    = f.label :min_age
    = f.number_field :min_age, min: 18, max: 100, value: 18
    = f.input :logo_url, as: :filepicker, label: "Logo", wrapper_html: { class: "image-picker" }
    = f.input :photos_url, as: :filepicker, label: "Photos", wrapper_html: { class: "image-picker" }
    = f.input :musics, as: :select, input_html: { class: "music-multiselect" }
    = f.input :opening_hours, as: :time, minute_step: 30, input_html: { class: "input-mini" }
    / = f.input :menu

  .form-actions
    = f.button :submit, class: "btn btn-primary"

app/views/bars/edit.html.haml
.page-header
  %h1 Editing bar

= render 'form'

= link_to 'Show', bars_path(@bar, format: :html), class: 'btn'
= link_to 'Back', bars_path(format: :html), class: 'btn'

app/views/bars/index.html.haml
.page-header
  %h1 Bars

%table.table.table-striped.table-bordered
  %tr
    %th Name
    %th Address
    %th Latitude
    %th Longitude
    %th Phone number
    %th Contact phone
    %th Min age
    %th Logo url
    %th Photos url
    %th Musics
    %th Opening Hours
    / %th Menu
    / %th Alcohol Prices
    %th Created At
    %th Weight
    %th

  - @bars.each do |bar|
    %tr
      %td= bar.name
      %td= bar.address
      %td= bar.lat
      %td= bar.lng
      %td= bar.phone_number
      %td= bar.contact_phone
      %td= bar.min_age
      %td= bar.logo_url
      %td= bar.photos_url
      %td= bar.musics.join(', ')
      %td= bar.opening_hours
      / %td= bar.menu
      / %td= bar.alcohol_prices
      %td= bar.created_at
      %td= bar.weight
      %td.center
        = link_to 'Show', bar_path(bar, format: :html), class: 'btn btn-mini btn-in-table'
        = link_to 'Edit', edit_bar_path(bar, format: :html), class: 'btn btn-mini btn-in-table'
        = link_to 'Delete', bar_path(bar, format: :html), method: :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-mini btn-danger btn-in-table'

%br

= link_to new_bar_path(format: :html), class: 'btn btn-success' do
  %i.icon-plus.icon-white
  new bar

app/views/bars/new.html.haml
.page-header
  %h1 New bar

= render 'form'

= link_to 'Back', bars_path(format: :html), class: 'btn'

app/views/bars/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @bar.name
%p
  %b Address:
  = @bar.address
%p
  %b Latitude:
  = @bar.lat
%p
  %b Longitude:
  = @bar.lng
%p
  %b Phone number:
  = @bar.phone_number
%p
  %b Contact phone:
  = @bar.contact_phone
%p
  %b Min age:
  = @bar.min_age
%p
  %b Logo:
  - if @bar.logo_url?
    = filepicker_image_tag @bar.logo_url, w: 160, h: 160, fit: 'clip'
  = @bar.logo_url
%p
  %b Photos:
  - if @bar.photos_url?
    = filepicker_image_tag @bar.photos_url, w: 160, h: 160, fit: 'clip'
    = @bar.photos_url
%p
  %b Music:
  = @bar.musics.join(', ')
%p
  %b Opening Hours:
  = @bar.opening_hours
/ %p
/   %b Menu:
/   = @bar.menu
/ %p
/   %b Alcohol Prices:
/   = @bar.alcohol_prices
%p
  %b Create At:
  = @bar.created_at
%p
  %b Weight:
  = @bar.weight

/ = link_to 'Edit', edit_bar_path(@bar, format: :html), class: 'btn'
= link_to 'Back', bars_path(format: :html), class: 'btn'