config/routes.rb
ZS::Application.routes.draw do

  devise_for :users

  root to: 'home#index'

  resources :bars
  resources :parties
  resources :clubs
  resources :lines
  resources :app_users

  namespace :api do
    get "search"
    get "zuller_my_night"
    get "parties"
  end

end

app/models/app_user.rb
require 'music_enums'

class AppUser
  include Mongoid::Document
  include Mongoid::Timestamps
  extend Enumerize

  field :devise_identifier, type: String
  field :fb_token, type: String
  field :fb_name, type: String
  field :age, type: Integer

  field :musical_preferences, type: Array
  enumerize :musical_preferences, in: Music.for_select, multiple: true

  field :past_attractions, type: Hash

  # field :location, type: GeoLocation
  # credites - embed many <Credit>
end

app/controllers/app_users_controller.rb
class AppUsersController < ApplicationController
  # GET /app_users
  # GET /app_users.json
  def index
    @app_users = AppUser.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @app_users }
    end
  end

  # GET /app_users/1
  # GET /app_users/1.json
  def show
    @app_user = AppUser.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @app_user }
    end
  end

  # GET /app_users/new
  # GET /app_users/new.json
  def new
    @app_user = AppUser.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @app_user }
    end
  end

  # GET /app_users/1/edit
  def edit
    @app_user = AppUser.find(params[:id])
  end

  # POST /app_users
  # POST /app_users.json
  def create
    @app_user = AppUser.new(params[:app_user])

    respond_to do |format|
      if @app_user.save
        format.html { redirect_to @app_user, notice: 'App user was successfully created.' }
        format.json { render json: @app_user, status: :created, location: @app_user }
      else
        format.html { render action: "new" }
        format.json { render json: @app_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /app_users/1
  # PUT /app_users/1.json
  def update
    @app_user = AppUser.find(params[:id])

    respond_to do |format|
      if @app_user.update_attributes(params[:app_user])
        format.html { redirect_to @app_user, notice: 'App user was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @app_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /app_users/1
  # DELETE /app_users/1.json
  def destroy
    @app_user = AppUser.find(params[:id])
    @app_user.destroy

    respond_to do |format|
      format.html { redirect_to app_users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/app_users_helper.rb
module AppUsersHelper
end

app/views/app_users/_form.html.haml
= simple_form_for(@app_user, format: :html) do |f|
  = f.error_notification

  .form-inputs
    = f.input :fb_name
    = f.input :fb_token
    = f.input :devise_identifier
    = f.label :age
    = f.number_field :age, min: 18, max: 100, value: 18
    = f.input :musical_preferences, as: :select, input_html: { class: "music-multiselect" }

  .form-actions
    = f.button :submit, class: "btn btn-primary"

app/views/app_users/edit.html.haml
.page-header
  %h1 Editing app_user

= render 'form'

= link_to 'Show', app_users_path(@app_user, format: :html), class: 'btn'
= link_to 'Back', app_users_path(format: :html), class: 'btn'

app/views/app_users/index.html.haml
.page-header
  %h1 App Users

%table.table.table-striped.table-bordered
  %tr
    %th fb Name:
    %th fb Token:
    %th Devise Identifier:
    %th Age:
    %th Musical Preferences:
    %th Past Attractions:
    %th Create At:
    %th

  - @app_users.each do |app_user|
    %tr
      %td= app_user.fb_name
      %td= app_user.fb_token
      %td= app_user.devise_identifier
      %td= app_user.age
      %td= app_user.musical_preferences.join(', ')
      %td= app_user.past_attractions
      %td= app_user.created_at
      %td.center
        = link_to 'Show', app_user_path(app_user, format: :html), class: 'btn btn-mini btn-in-table'
        = link_to 'Edit', edit_app_user_path(app_user, format: :html), class: 'btn btn-mini btn-in-table'
        = link_to 'Delete', app_user_path(app_user, format: :html), method: :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-mini btn-danger btn-in-table'

%br

= link_to new_app_user_path(format: :html), class: 'btn btn-success' do
  %i.icon-plus.icon-white
  new app user

app/views/app_users/new.html.haml
.page-header
  %h1 New AppUser

= render 'form'

= link_to 'Back', app_users_path(format: :html), class: 'btn'

app/views/app_users/show.html.haml
%p#notice= notice

%p
  %b fb Name:
  = @app_user.fb_name
%p
  %b fb Token:
  = @app_user.fb_token
%p
  %b Devise Identifier:
  = @app_user.devise_identifier
%p
  %b Age:
  = @app_user.age
%p
  %b Musical Preferences:
  = @app_user.musical_preferences.join(', ')
%p
  %b Past Attractions:
  = @app_user.past_attractions
%p
  %b Create At:
  = @app_user.created_at

= link_to 'Edit', edit_app_user_path(@app_user, format: :html), class: 'btn'
= link_to 'Back', app_users_path(format: :html), class: 'btn'